### ISSUE TITLE
imgui-sfml/2.1 Allow the version of Dear ImGui to be configurable

### ISSUE THREAD

**Issue by fgallegosalido** [bincrafters/community#1349]
### Description of your feature

The recipe for imgui-sfml is currently using Dear ImGui version 1.75 (v1.80 has just been realeased). It was discussed in #1125 whether or not the version should be configurable.

Because of the nature of Dear ImGui, it's not possible for imgui-sfml to have imgui as a dependency (or at least not in the conventional way). For that reason, the sources of Dear ImGui must be downloaded in order to build imgui-sfml.

The conventions require that all the sources that are part of a recipe should be listed in the corresponding `conandata.yml`. It was sugested that, in order to support different Dear ImGui versions, the sources of every supported version must be listed (along with the sha256 checksum), and select the one that corresponds to the selected Dear ImGui version.

I have a proposed solution that works until 1.79. For v1.80, we have to build the `imgui_tables.cpp` file too, which depends on imgui-sfml releasing a new version. It'd be a good moment to also build the `imgui_demo.cpp` file as part of the library.

### Proposed solution

The proposed solution defines a new option, `imgui_version`, with the possible values `["1.75", "1.76", "1.77", "1.78", "1.79"]`, and defaulted to `"1.79"`. Then, in the `source(self)` function, we get the corresponding imgui source according to the value of `imgui_version`.

The code looks like this:

```python
def _imgui_source(self):
    for source in self.conan_data["sources"][self.version][1:]:
        if self.options.imgui_version.value in source["url"]:
            return source
    # This exception might not be necessary, as limiting the possible values for imgui_version should be enough
    raise ConanInvalidConfiguration("Provided Dear ImGui version doesn't exist")

def source(self):
    tools.get(**self.conan_data["sources"][self.version][0])
    extracted_dir = self.name + "-" + self.version
    os.rename(extracted_dir, self._source_subfolder)

    tools.get(**self._imgui_source())
    extracted_dir = glob.glob("imgui-*")[0]
    os.rename(extracted_dir, self._imgui_subfolder)
```

**Comment by Croydon** [comment]
Sorry, for the silence. Too much is going on as always. I will soon-ish try to migrate the recipe to our central repository (this one right here). After that, PRs are very much welcome (as they were previously, but it is harder with single recipe repositories)

**Comment by fgallegosalido** [comment]
Thank you for the response! I'm pretty much open to help where necessary

**Comment by Croydon** [comment]
@fgallegosalido Please have a look and let me know what you think about this solution I applied

https://github.com/bincrafters/community/tree/main/recipes/imgui-sfml/all

**Comment by fgallegosalido** [comment]
I'm not 100% sure how the sources should be listed in the `conandata.yml`. I'm thinking maybe a better layout could be this one:

```yml
sources:
  "2.1":
    - url: "https://github.com/eliasdaler/imgui-sfml/archive/v2.1.tar.gz"
      sha256: "16a589cb7219ebe3147b13cfe44e50de315deedf6ca8bd67d4ef91de3a09478e"
  imgui:
    "1.75":
      - url: "https://github.com/ocornut/imgui/archive/v1.75.tar.gz"
        sha256: "1023227fae4cf9c8032f56afcaea8902e9bfaad6d9094d6e48fb8f3903c7b866"
    "1.76":
      - url: "https://github.com/ocornut/imgui/archive/v1.76.tar.gz"
        sha256: "e482dda81330d38c87bd81597cacaa89f05e20ed2c4c4a93a64322e97565f6dc"
    "1.77":
      - url: "https://github.com/ocornut/imgui/archive/v1.77.tar.gz"
        sha256: "c0dae830025d4a1a169df97409709f40d9dfa19f8fc96b550052224cbb238fa8"
    "1.78":
      - url: "https://github.com/ocornut/imgui/archive/v1.78.tar.gz"
        sha256: "f70bbb17581ee2bd42fda526d9c3dc1a5165f3847ff047483d4d7980e166f9a3"
    "1.79":
      - url: "https://github.com/ocornut/imgui/archive/v1.79.tar.gz"
        sha256: "f1908501f6dc6db8a4d572c29259847f6f882684b10488d3a8d2da31744cd0a4"
patches:
  "2.1":
    - patch_file: "patches/0001-conan-libs.patch"
      base_path: "source_subfolder"

```

This way we can access the exact sources this way:

```python
def source(self):
    tools.get(**self.conan_data["sources"][self.version][0])
    extracted_dir = self.name + "-" + self.version
    os.rename(extracted_dir, self._source_subfolder)

    tools.get(**self.conan_data["sources"]["imgui"][self.options.imgui_version][0])
    extracted_dir = glob.glob("imgui-*")[0]
    os.rename(extracted_dir, self._imgui_subfolder)
```

Maybe we have to tweak the `self.conan_data["sources"]["imgui"][self.options.imgui_version][0]` part because Python it's not taking very well `self.options.imgui_version` as the key value. These three options seem to work:

- `str(self.options.imgui_version)`
-  `self.options.imgui_version.value` (I think this one is the most idiomatic)
- `f"{self.options.imgui_version}"`

**Comment by Croydon** [comment]
I agree that the current way is not perfect as it requires to duplicate the download for imgui-sfml itself. 

I would like to keep our recipes compatible with Conan Center Index standards as far as possible. The `conandata.yml` file is getting reduced to entries for the exported version only. Meaning, all entries we use have to be under the `2.1` key (in this example). We also can't freely change the structure of the YAML file.

If you want to try out what is possible, please test with the hooks installed and enabled: https://github.com/conan-io/hooks/

>  part because Python it's not taking very well self.options.imgui_version as the key value

I'm not sure what the problem is, but if it needs to be changed than `str(self.options.imgui_version)` might be the best way. IIRC `.values` for options and settings should be avoided and we can't use Python's f strings yet as we still have to support Python 2.7 for the support period of Conan 1.x

**Comment by fgallegosalido** [comment]
Okay, I think this layout is compatible with the Conan Center Index standards:

```yml
sources:
  "2.1":
    imgui-sfml:
      url: "https://github.com/eliasdaler/imgui-sfml/archive/v2.1.tar.gz"
      sha256: "16a589cb7219ebe3147b13cfe44e50de315deedf6ca8bd67d4ef91de3a09478e"
    imgui:
      "1.75":
        url: "https://github.com/ocornut/imgui/archive/v1.75.tar.gz"
        sha256: "1023227fae4cf9c8032f56afcaea8902e9bfaad6d9094d6e48fb8f3903c7b866"
      "1.76":
        url: "https://github.com/ocornut/imgui/archive/v1.76.tar.gz"
        sha256: "e482dda81330d38c87bd81597cacaa89f05e20ed2c4c4a93a64322e97565f6dc"
      "1.77":
        url: "https://github.com/ocornut/imgui/archive/v1.77.tar.gz"
        sha256: "c0dae830025d4a1a169df97409709f40d9dfa19f8fc96b550052224cbb238fa8"
      "1.78":
        url: "https://github.com/ocornut/imgui/archive/v1.78.tar.gz"
        sha256: "f70bbb17581ee2bd42fda526d9c3dc1a5165f3847ff047483d4d7980e166f9a3"
      "1.79":
        url: "https://github.com/ocornut/imgui/archive/v1.79.tar.gz"
        sha256: "f1908501f6dc6db8a4d572c29259847f6f882684b10488d3a8d2da31744cd0a4"
patches:
  "2.1":
    - patch_file: "patches/0001-conan-libs.patch"
      base_path: "source_subfolder"
```

I made sure to check with the conan-center hook. Despite some errors (that I'm not sure how to fix, if they have to), it seems to build fine. It avoids repetition of the sources under the same version. If imgui-sfml releases a new version, then the repetition of the imgui sources is probably unavoidable, but I guess that's the price to pay for conformace with the Conan Center Index.
