### ISSUE TITLE
Ability to apply conan config install for all recipes

### ISSUE THREAD

**Issue by rockdreamer** [bincrafters/community#1382]
As a maintainer of a medium sized set of packages for a company using Conan/Artifactory, I'd like to be able to use something like bincrafters/templates to build them.

Our current workflow is based around applying a conan config install command before running any recipe.

Ideally I'd like to be able to add a .bincrafters-package-tools.yml file in the root of the repository with contents like:
```yaml
---
conan_configuration_sources:
  - url: https://github.com/ccdc-opensource/conan-ccdc-common-configuration.git
    type: git
    args: -b main
```
And all builds will run `conan config install --type git --args -b main https://github.com/ccdc-opensource/conan-ccdc-common-configuration.git` before any other command.
