### ISSUE TITLE
Long builds and appveyor limitations

### ISSUE THREAD

**Issue by sigmoidal** [bincrafters/community#37]
It seems that currently our Appveyor template goes ahead and builds all configurations for a given compiler in a single build-process, i.e. debug/release/x86/x86_64/static/shared, etc.

According to Appveyor's Time limitations: All plans have 60 minutes quota per build job.

I propose that we modify the template to split the build processes  by default. Either by build_type:

```
configuration:
  - Debug
  - Release
```

or by arch:
```
platform:
  - x86
  - x64
```

I also propose that builds on our CI should be marked failed immediately on error of just one build, using:

```
matrix:
    fast_finish: true
```

This way build threads are not occupied. Our CI is there to ensure that in the end all builds are correct and green, so it makes no sense to let appveyor keep building configurations even if one fails.

I prefer the arch approach of splitting builds. We also shouldn't over-partition the builds as that will be a waste probably (so no need to split by arch and build type at the same time).

The disadvantage is that each build process needs to initialize the image environment, fetch sources etc.
The advantages however as far as I can tell are (a) reduce the chance of a timeout due to a long build process, (b) easier to debug when things fail.

I am not sure if there are issues with this, otherwise I can submit a PR to the templates, so we can adopt on the recipe upgrade sprint across packages.

**Comment by sigmoidal** [comment]
Are there implications with the `platform` approach when cross-compiling other than x86/x64 ?

**Comment by uilianries** [comment]
Usually I split Conan jobs by arch and build_type:

```
matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_ARCHS: "x86"
      CONAN_BUILD_TYPES: "Release"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_ARCHS: "x86_64"
      CONAN_BUILD_TYPES: "Release"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_ARCHS: "x86"
      CONAN_BUILD_TYPES: "Debug"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_ARCHS: "x86_64"
      CONAN_BUILD_TYPES: "Debug"
```

I don't know which advantages we could aggregate by using `configuration` and `platform`  directly from AppVeyor.
